server:
  port: 8080  # API Gateway portu
spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      profile: dev
      label: master
