server:
  port: 8085
spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      profile: dev
      label: master