server:
  port: 8082
spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8001
      profile: dev
      label: master