spring:
  cloud:
    stream:
      defaultBinder: rabbit  # Kafka veya rabbit olarak değiştirebilirsiniz
      function:
        bindings:
          processCustomerEvent-in-0: customer-topic  # 'processCustomerEvent' fonksiyonunu 'customer-topic' ile bağla
      bindings:
        processCustomerEvent-in-0:
          destination: customer-topic
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092
          consumerProperties:
            group.id: order-service-group  # Özelleştirilmiş bir grup kimliği
            auto-offset-reset: latest      # En son offsetten başlamak için

      rabbit:
        binder:
          addresses: localhost:5672
          username: guest
          password: guest
  application:
    name: order-service
jwt:
  expiration: 600000
  key: C53m0R5fXD2VXQwoWbV6Rhqk44l/fY0n6rk67028lFw9ZCU9nIpc0V6N1S7hNGHSj6nNGKszIHMUCGxOwatyQXtcA+HmkiCGtO19bhhVEEhfDVxdYP/PLDTnolseuAMP9bYYmXPUXZ/79iRq90kIsM37Uiw/Q3xFFjHObjzzD78ZP8ucmaavcEBTeW9dpOieMvyS7Zdz4ut/slMtIpq1gKBKBw+r3e3sUbUGmoINGJoBsPEQflbE10J1aTRLLREq1EmUNw9VZmVOtCrVErwKawkQFVniWieqAeQze+OY1BfkjYI11lhO7Y7LyOl3Vx35EezWhrYj8ceajsnEr7CIMg==
server:
  port: 8082