spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/halitkalayci/common-microservices-configuration
          default-label: master
          searchPaths: "{application}"

server:
  port: 8001
